language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
    - SYMFONY_VERSION=^2.3.3
    - SYMFONY_VERSION=^2.8.0
    - SYMFONY_VERSION=^3.0
    - SYMFONY_VERSION=^4.0

matrix:
  exclude:
  - php: 5.6
    env: SYMFONY_VERSION=^4.0
  - php: 7.0
    env: SYMFONY_VERSION=^4.0

install:
  - composer require "symfony/framework-bundle:${SYMFONY_VERSION}" "symfony/console:${SYMFONY_VERSION}"

script: ./vendor/bin/phpunit -v
